version: '3.3'
services:
    game:
        container_name: game
        image: "lucas.volgarini/jogo-velha:1.0.0-SNAPSHOT"
        ports:
            - '8090:8080'
        networks:
            - production-network

networks:
    production-network:
        driver: bridge